import CssBaseline from '@mui/joy/CssBaseline';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import ThemeProvider from '../ThemeProvider';
import App from './app';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <CssBaseline />
            <App>{children}</App>
        </ThemeProvider>
      </body>
    </html>
  );
}
