name: PR-Release

on:
  pull_request:
    branches:
      - main
    paths:
      - "web/**"

jobs:
  pr-draft-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get the PR number
        uses: actions/github-script@v7
        id: get_pr_data
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              throw new Error('No pull request found');
            }
            return pr;

      - name: Save version from PR number
        id: save_version
        run: |
          echo "version=0.0.0-PR.${{ fromJson(steps.get_pr_data.outputs.result).number }}" >> "$GITHUB_OUTPUT"
          echo "pr_number=PR-${{ fromJson(steps.get_pr_data.outputs.result).number }}" >> "$GITHUB_OUTPUT"

      - name: Replace version in package.json
        run: echo "`jq '.version="${{ steps.save_version.outputs.version }}"' ./package.json`" > ./package.json

      - name: Install the dependencies
        run: yarn install --frozen-lockfile --network-timeout 500000

      - name: Build the application
        run: yarn build

      - uses: FirebaseExtended/action-hosting-deploy@v0.9.0
        with:
          firebaseServiceAccount: "${{ secrets.GCP_SA_KEY }}"
          projectId: scrappy-prod
          channelId: ${{steps.save_version.outputs.pr_number}}
          repoToken: "${{ secrets.GITHUB_TOKEN }}"

      # - name: Deploy to Firebase Hosting
      #   uses: w9jds/firebase-action@v13.7.2
      #   with:
      #     args: hosting:channel:deploy ${{ steps.save_version.outputs.pr_number }} --expires 1h
      #   env:
      #     GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      # - name: Get Firebase Hosting URL
      #   id: get-url
      #   run: echo "URL=https://<YOUR_FIREBASE_PROJECT_ID>.web.app" >> $GITHUB_ENV

      # - name: Add comment to PR with Firebase Hosting URL
      #   uses: actions/github-script@v7
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}

      #     script: |
      #       const url = process.env.URL;
      #       console.log('url = ',url)
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: '👋 Thanks for reporting!'
      #       })
