name: PR-Release

on: workflow_dispatch

permissions:
  contents: write
  pull-requests: read

jobs:
  pr-draft-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.save_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/github-script@v7
        id: get_pr_data
        with:
          script: |
            const result = (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            );
            console.log(result);
            if (!result.data.length) {
              throw new Error('No PR found for the commit');
            }
            return result.data[0];

      - name: Save version from PR number
        id: save_version
        run: |
          echo "version=0.0.0-PR.${{ fromJson(steps.get_pr_data.outputs.result).number }}" >> "$GITHUB_OUTPUT"

      - name: Replace version in package.json
        run: echo "`jq '.version="${{ steps.save_version.outputs.version }}"' release/app/package.json`" > release/app/package.json

      - run: echo "PACKAGE_JSON=$(jq -c . < release/app/package.json)" >> $GITHUB_ENV
      - run: echo '${{ fromJson(env.PACKAGE_JSON).version }}'
